- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=1024"]
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: ["--fix=lf"]
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: flake8
      exclude: migrations\/[^/]*\.py$|settings\.py$|vendor\/[^/]*\.*$|assets\/[^/]*\.*$
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
    - id: isort
      exclude: migrations\/[^/]*\.py$
-   repo: local
    hooks:
    -   id: django-migrations
        name: Django unmigrated changes
        description: 'This hook checks for unmigrated changes'
        entry: sh -c "! poetry run parts makemigrations --dry-run --exit"
        language: system
        files: \.py$
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
    - id: forbid-tabs
      exclude: Makefile|\.bat$|vendor\/|assets\/
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.4
  hooks:
    - id: python-bandit-vulnerability-check
      args: [--recursive]
