[tool.poetry]
name = "django-okta-auth"
version = "0.1.0"
description = "Django Authentication for Okta OpenID"
authors = ["Matt Magin <matt.magin@cmv.com.au>"]
license = "MIT"
packages = [
    {include = "okta_oauth2"}
]

[tool.poetry.dependencies]
python = "^3.6"
Django = ">=1.11.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
